prpath: "D:\\OpenText\\Home\\content\\bin"
impath: "D:\\OpenText\\Home\\bin\\bin\\mservlet"
tempDir: "D:\\OpenText\\Artesia\\temp"
prep: bulkimport.bat -user tsuper -password Otmm@123 -mode files -dir "{0}" -nodelete -profile Product -folder {1} -createfolder D:\OpenText\Home\imconv\conf\folder.properties > "D:\OpenText\Home\imconv\logs\cbutil\cbutil-create-logs_{2}.txt"
aiprep: bulkimport.bat -user tsuper -password Otmm@123 -mode xml -dir "{0}" -nodelete -profile Product -folder {1} -createfolder D:\OpenText\Home\imconv\conf\folder.properties > "D:\OpenText\Home\imconv\logs\cbutil\cbutil-import-logs_{2}.txt"
imprep: run.bat {0} {1} {2} {3}
log: D:\OpenText\Home\imconv\logs\cbutil\job-status.log
data: dHN1cGVyO090bW1AMTIz