util-path: "E:\\OpenText\\Home\\content\\bin"
command: bulkimport.bat -user tsuper -password Otmm@123 -mode files -dir {0} -nodelete -profile Product -folder {1} -createfolder E:\OpenText\Home\imconv\webapps\cbutil\folder.properties > E:\OpenText\Home\imconv\webapps\cbutil\logs.txt
log: E:\OpenText\Home\imconv\webapps\cbutil\logs.txt
