prpath: "E:\\OpenText\\Home\\content\\bin"
impath: "E:\test"
tempDir: "E:\test"
prep: bulkimport.bat -user tsuper -password Otmm@123 -mode files -dir {0} -nodelete -profile Product -folder {1} -createfolder E:\OpenText\Home\imconv\conf\folder.properties > E:\OpenText\Home\imconv\logs\cbutil-logs.txt
imprep: bulk.bat -b -dir {0} -folder {1} -rdset default -profile Product -impex E:\OpenText\Home\imconv\conf\impex.properties -url http://localhost:11090/ot-damlink/ImConvServlet > E:\OpenText\Home\imconv\logs\cbutil-logs.txt
log: E:\OpenText\Home\imconv\logs\job-status.log
data: dHN1cGVyO090bW1AMTIz
#{0] - asset directory, {1} - folder-id-from-otmm,